insert into users(name, last_name, login, password, email)
values ('user', 'user', 'user', '1234', 'user@user.com'),
       ('admin', 'admin', 'admin', '1234', 'admin@admin.com');

insert into roles(id, role)
values (1, 'user'),
       (2, 'admin');

insert into authors(first_name, last_name)
values ('ali', 'jalil'),
       ('haider', 'hassan'),
       ('ziad', 'ahmed'),
       ('kamel', 'khalil'),
       ('kag', 'jon'),
       ('zara', 'khalid'),
       ('zah', 'jonrdn'),
       ('dasha', 'ali'),
       ('sasha', 'max'),
       ('nasty', 'mohamed');

insert into news(author_id, title, short_text, full_text)
values (1,
        'As Trump',
        'As the pandemic worsens, major retailers, grocery stores,  ',
        'isn''t leading America much as its pandemic worsens. But that''s not stopping Walmart -- along with Kroger, Kohl''s, and city and state leaders and officials -- from making the tough decisions that the President has shirked.'),
       (1,
        'Take a closer look',
        'World''s population could fall by half a billion',
        'is likely to peak at 9.7 billion in 2064, and then decline to about 8.8 billion by the end of the century, as women get better access to education and contraception, a new study has found'),
       (1,
        'Featured',
        'Quest took his first flight in months. Here''s what he now ',
        'It was my first flight in nearly four months after the longest separation I''ve had from aviation in 35 or 40 years.And it was emotional.Because essential work meant I needed to travel between New York and London, I caught a United Airlines flight from Newark to Heathrow. It''s a flight I''ve done so many times.'),
       (2,
        'Life during a pandemic',
        'Private island just sold for $6 million. The buyer only saw it in a video tour',
        'A private island off the coast of Ireland boasting three beaches, seven houses and natural wildlife has been sold for more than $6.3 million -- with the anonymous buyer not even visiting the location in person before going through with the purchase..'),
       (2, 'Sports',
        'Before taking her own life, South Korean triathlete asked her mother ',
        'But Choi Young-hee''s pride is one filled with remorse as he talks to CNN Sport following his daughter''s death ​last month.After the death of 22-year-old Choi Suk-hyeon, ​her teammates came forward with horrifying ​allegations ​about what they say is their triathlon team''s physically and emotionally abusive training practices.'),
       (2,
        'From the Midlands',
        'From the Midlands to Madrid, the life of trailblazing Black footballer Laurie ',
        'Darren Moore vividly recalls sitting at home as an eight-year-old, staring at the television in wide-eyed amazement.On the screen were 22 men running around a pitch and kicking a ball. "That''s a football match," Moore''s father told him. From that moment, Moore knew what he wanted to do in life.'),
       (3,
        'Rare color',
        'Rare color photos cast new light on World War II',
        'olor film was rare in World War II. The vast majority of the photos taken during the conflict were in black and white, and color photography as a whole was still a relatively new technique.'),
       (3,
        'Luo Yang',
        'Luo Yang''s powerful female portraits challenge Chinese gender norms',
        'or Chinese photographer Luo Yang, girlhood has a multitude of meanings. But rather than relying on the type of saccharine depictions often used in China to depict young women -- gentle, delicate, and overly feminine -- Luo''s project "Girls" features edgy and alternative subjects who defy stereotype and expectation'),
       (3,
        'The best',
        'The best blenders of 2020',
        'Smoothies, soups and salsas. Nut butters, milkshakes and margaritas. Puddings, dips and batters. If any of this sounds like the making of the menu of your dreams, a kitchen blender should be at the top of your small appliance wish list.'),
       (4,
        'What',
        'What''s behind Tucker Carlson''s mask',
        'Jill Filipovic is a journalist based in New York and author of the book "The H-Spot: The Feminist Pursuit of Happiness." Follow her on Twitter. The opinions expressed in this commentary are solely her own. View more opinion articles on CNN.'),
       (4,
        'Jill Filipovic',
        'This article quotes racist, homophobic and sexist language',
        'Tucker Carlson, the Fox News host with the highest-rated show on cable television, has a white supremacy problem: Racism, bigotry, homophobia and misogyny just seem to follow him wherever he goes'),
       (4,
        'Kansas congressman',
        'Kansas congressman faces felony charges related to 2019 local election',
        'Republican Rep. Steve Watkins of Kansas faces three felony charges and one misdemeanor related to a 2019 local election, Shawnee County District Attorney Mike Kagay announced Tuesday'),
       (5,
        'DeSantis downplayed',
        'DeSantis downplayed coronavirus help from New York after ',
        'lorida Gov. Ron DeSantis publicly downplayed New York''s role in providing his state with shipments of an antiviral drug to help combat the coronavirus pandemic after a staffer in The Sunshine State''s health department had privately praised the assistance, CNN has learned'),
       (5,
        'See Sessions',
        'See Sessions respond after losing Alabama GOP Senate runoff',
        'Jeff Sessions speaks after losing an Alabama Senate GOP primary runoff to former Auburn University football coach Tommy Tuberville'),
       (5,
        'Actor Sylvester Stallone',
        'Actor Sylvester Stallone Selling La Quinta, California, Villa at a Loss', 'Rocky” star Sylvester Stallone is selling his abode in La Quinta, California, for $3.35 million, about $1.15 million less than what he paid for it a decade ago.The Mediterranean- and Tuscan- style villa has 4,889 square feet of interior space, including four bedrooms and five baths, according to the listing with Josh Reef of Douglas Elliman, who listed the property Wednesday'),
       (6,
        'Will Jeff',
        'Will Jeff Sessions have the last laugh on Donald Trump on Tuesday',
        'On Tuesday night in Alabama, the man Donald Trump made famous (and then infamous) is seeking to make an unlikely political comeback. Jeff Sessions, who vacated his Senate seat to serve as Trump''s first attorney general only to be publicly castigated and humiliated by the President for his decision to recuse himself in the Russia probe, is trying to take back the seat'),
       (6,
        'House Democrats',
        'House Democrats ask Supreme Court to speed things up in Trump financial docs cases',
        'The House of Representatives asked the Supreme Court late Monday night to move faster so it can begin a renewed attempt to obtain documents from President Donald Trump''s financial firms'),
       (7,
        'Fact check',
        'Fact check: Trump makes at least 19 false or misleading ',
        'Speaking in the White House Rose Garden, at what was billed as a "press conference" in which he would give remarks about China, Trump delivered a rambling 52-minute monologue filled with pre-scripted attacks on Democratic opponent Joe Biden'),
       (7,
        'Here',
        'Here''s the most incredible thing about Donald Trump''s problem with facts',
        'Which is stunning -- a mountain of exaggerations, half-truths and outright falsehoods constructed by the President as he seeks to invalidate the very notion of facts and truth'),
       (8,
        'You won',
        'You won''t believe what Donald Trump just said about coronavirus testing',
        'On Monday afternoon, President Donald Trump was asked about his insistence that the only reason that coronavirus cases are spiking across the South and Southwest was an increase in testing. His answer was, uh, something else');

insert into tags(name, news_id)
values ('sport', 1),
       ('Policy', 1),
       ('philosophy', 1),
       ('chemistry', 2),
       ('physics', 2),
       ('Mathematics', 2),
       ('Arabic', 3),
       ('English', 3),
       ('the Russian language', 3),
       ('biology', 4),
       ('Islamic education', 4),
       ('psychology', 4),
       ('Anthropology', 5),
       ('Sociology', 5),
       ('literature', 5),
       ('Stories', 6),
       ('a novel', 6),
       ('prose', 6),
       ('short story', 7),
       ('Fashion', 7),
       ('Comedy', 7),
       ('tragic', 8),
       ('Stage', 8),
       ('take photo', 8),
       ('Market', 9),
       ('Counting', 9),
       ('Debt', 9),
       ('Loans', 10),
       ('Electricity', 10),
       ('Architectural', 10),
       ('Laser engineering', 11),
       ('Software Engineering', 11),
       ('Walking sport', 11),
       ('Sports jumping', 12),
       ('Basketball', 12),
       ('Football', 12),
       ('Volley ball', 13),
       ('Beach ball', 13),
       ('The water ball', 13),
       ('Oklahoma scandal', 14),
       ('Scandals', 14),
       ('Political corruption', 14),
       ('Financial corruption', 15),
       ('Moral corruption', 15),
       ('Social deprivation', 15),
       ('Old Testament', 16),
       ('new era', 16),
       ('Antiquity', 16),
       ('Dark Ages', 17),
       ('Ice ages', 17),
       ('middle Ages', 17),
       ('the new era', 18),
       ('Hair', 18),
       ('Romantic poetry', 18),
       ('folk poetry', 19),
       (' Pre-Islamic Poetry', 19),
       ('Modern poetry', 19),
       ('Cartoon stories', 20),
       ('Imagination stories', 20),
       ('Romantic movie', 20)